export type PatchSourceKind = 'riot' | 'steam' | 'rss' | 'html';

export interface PatchSource {
  id: string;
  name: string;
  category: 'Riot Games' | 'FPS' | 'MMO & RPG' | 'Survie & sandbox' | 'Strategy' | 'Software';
  kind: PatchSourceKind;
  color: number;
  iconUrl?: string;
  steamAppId?: number;
  indexUrl?: string;
  rssUrl?: string;
  linkPattern?: string;
  matchKeywords?: string[];
  homeUrl: string;
}

const RIOT_COLOR = 0xd13639;
const STEAM_COLOR = 0x1b2838;
const SOFTWARE_COLOR = 0x5865f2;

export const PATCH_SOURCES: PatchSource[] = [
  {
    id: 'league-of-legends',
    name: 'League of Legends',
    category: 'Riot Games',
    kind: 'riot',
    color: RIOT_COLOR,
    iconUrl: 'https://ddragon.leagueoflegends.com/cdn/14.24.1/img/profileicon/29.png',
    indexUrl: 'https://www.leagueoflegends.com/fr-fr/news/tags/patch-notes/',
    linkPattern: '/fr-fr/news/game-updates/',
    homeUrl: 'https://www.leagueoflegends.com/fr-fr/news/tags/patch-notes/',
  },
  {
    id: 'teamfight-tactics',
    name: 'Teamfight Tactics',
    category: 'Riot Games',
    kind: 'riot',
    color: RIOT_COLOR,
    iconUrl:
      'https://cmsassets.rgpub.io/sanity/images/dsfx7636/news_live/0cfcf07fd39de46b087850b861bcd14b1e0f5f2a-1920x1080.jpg',
    indexUrl: 'https://teamfighttactics.leagueoflegends.com/fr-fr/news/tags/patch-notes/',
    linkPattern: '/fr-fr/news/game-updates/',
    homeUrl: 'https://teamfighttactics.leagueoflegends.com/fr-fr/news/tags/patch-notes/',
  },
  {
    id: 'valorant',
    name: 'VALORANT',
    category: 'Riot Games',
    kind: 'riot',
    color: RIOT_COLOR,
    iconUrl:
      'https://cmsassets.rgpub.io/sanity/images/dsfx7636/news_live/6c73905e89071a77b932e62c2264e28b7f672de5-1920x1080.jpg',
    indexUrl: 'https://playvalorant.com/fr-fr/news/tags/patch-notes/',
    linkPattern: '/fr-fr/news/game-updates/',
    homeUrl: 'https://playvalorant.com/fr-fr/news/tags/patch-notes/',
  },
  {
    id: 'counter-strike-2',
    name: 'Counter-Strike 2',
    category: 'FPS',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 730,
    homeUrl: 'https://store.steampowered.com/app/730',
  },
  {
    id: 'dota-2',
    name: 'Dota 2',
    category: 'Strategy',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 570,
    homeUrl: 'https://store.steampowered.com/app/570',
  },
  {
    id: 'apex-legends',
    name: 'Apex Legends',
    category: 'FPS',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1172470,
    homeUrl: 'https://store.steampowered.com/app/1172470',
  },
  {
    id: 'pubg',
    name: 'PUBG: BATTLEGROUNDS',
    category: 'FPS',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 578080,
    homeUrl: 'https://store.steampowered.com/app/578080',
  },
  {
    id: 'rainbow-six-siege',
    name: 'Rainbow Six Siege',
    category: 'FPS',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 359550,
    homeUrl: 'https://store.steampowered.com/app/359550',
  },
  {
    id: 'warframe',
    name: 'Warframe',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 230410,
    homeUrl: 'https://store.steampowered.com/app/230410',
  },
  {
    id: 'path-of-exile',
    name: 'Path of Exile',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 238960,
    homeUrl: 'https://store.steampowered.com/app/238960',
  },
  {
    id: 'lost-ark',
    name: 'Lost Ark',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1599340,
    homeUrl: 'https://store.steampowered.com/app/1599340',
  },
  {
    id: 'new-world',
    name: 'New World: Aeternum',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1063730,
    homeUrl: 'https://store.steampowered.com/app/1063730',
  },
  {
    id: 'elder-scrolls-online',
    name: 'The Elder Scrolls Online',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 306130,
    homeUrl: 'https://store.steampowered.com/app/306130',
  },
  {
    id: 'rust',
    name: 'Rust',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 252490,
    homeUrl: 'https://store.steampowered.com/app/252490',
  },
  {
    id: 'ark-survival-ascended',
    name: 'ARK: Survival Ascended',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 2399830,
    homeUrl: 'https://store.steampowered.com/app/2399830',
  },
  {
    id: 'ark-survival-evolved',
    name: 'ARK: Survival Evolved',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 346110,
    homeUrl: 'https://store.steampowered.com/app/346110',
  },
  {
    id: 'valheim',
    name: 'Valheim',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 892970,
    homeUrl: 'https://store.steampowered.com/app/892970',
  },
  {
    id: 'palworld',
    name: 'Palworld',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1623730,
    homeUrl: 'https://store.steampowered.com/app/1623730',
  },
  {
    id: 'terraria',
    name: 'Terraria',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 105600,
    homeUrl: 'https://store.steampowered.com/app/105600',
  },
  {
    id: 'stardew-valley',
    name: 'Stardew Valley',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 413150,
    homeUrl: 'https://store.steampowered.com/app/413150',
  },
  {
    id: 'no-mans-sky',
    name: "No Man's Sky",
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 275850,
    homeUrl: 'https://store.steampowered.com/app/275850',
  },
  {
    id: 'satisfactory',
    name: 'Satisfactory',
    category: 'Survie & sandbox',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 526870,
    homeUrl: 'https://store.steampowered.com/app/526870',
  },
  {
    id: 'factorio',
    name: 'Factorio',
    category: 'Strategy',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 427520,
    homeUrl: 'https://store.steampowered.com/app/427520',
  },
  {
    id: 'rimworld',
    name: 'RimWorld',
    category: 'Strategy',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 294100,
    homeUrl: 'https://store.steampowered.com/app/294100',
  },
  {
    id: 'stellaris',
    name: 'Stellaris',
    category: 'Strategy',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 281990,
    homeUrl: 'https://store.steampowered.com/app/281990',
  },
  {
    id: 'crusader-kings-3',
    name: 'Crusader Kings III',
    category: 'Strategy',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1158310,
    homeUrl: 'https://store.steampowered.com/app/1158310',
  },
  {
    id: 'civilization-vi',
    name: "Sid Meier's Civilization VI",
    category: 'Strategy',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 289070,
    homeUrl: 'https://store.steampowered.com/app/289070',
  },
  {
    id: 'dead-by-daylight',
    name: 'Dead by Daylight',
    category: 'FPS',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 381210,
    homeUrl: 'https://store.steampowered.com/app/381210',
  },
  {
    id: 'helldivers-2',
    name: 'HELLDIVERS 2',
    category: 'FPS',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 553850,
    homeUrl: 'https://store.steampowered.com/app/553850',
  },
  {
    id: 'destiny-2',
    name: 'Destiny 2',
    category: 'FPS',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1085660,
    homeUrl: 'https://store.steampowered.com/app/1085660',
  },
  {
    id: 'baldurs-gate-3',
    name: "Baldur's Gate 3",
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1086940,
    homeUrl: 'https://store.steampowered.com/app/1086940',
  },
  {
    id: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1091500,
    homeUrl: 'https://store.steampowered.com/app/1091500',
  },
  {
    id: 'elden-ring',
    name: 'ELDEN RING',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 1245620,
    homeUrl: 'https://store.steampowered.com/app/1245620',
  },
  {
    id: 'monster-hunter-world',
    name: 'Monster Hunter: World',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 582010,
    homeUrl: 'https://store.steampowered.com/app/582010',
  },
  {
    id: 'monster-hunter-wilds',
    name: 'Monster Hunter Wilds',
    category: 'MMO & RPG',
    kind: 'steam',
    color: STEAM_COLOR,
    steamAppId: 2246340,
    homeUrl: 'https://store.steampowered.com/app/2246340',
  },
  {
    id: 'nvidia-geforce-drivers',
    name: 'NVIDIA GeForce Drivers',
    category: 'Software',
    kind: 'html',
    color: 0x76b900,
    iconUrl: 'https://www.nvidia.com/favicon.ico',
    indexUrl: 'https://www.nvidia.com/en-us/geforce/news/',
    linkPattern: '/en-us/geforce/news/',
    matchKeywords: ['driver', 'game ready', 'studio driver'],
    homeUrl: 'https://www.nvidia.com/en-us/geforce/drivers/',
  },
  {
    id: 'amd-radeon-drivers',
    name: 'AMD Radeon Drivers',
    category: 'Software',
    kind: 'html',
    color: 0xed1c24,
    iconUrl: 'https://www.amd.com/favicon.ico',
    indexUrl: 'https://www.amd.com/en/resources/support-articles/release-notes.html',
    linkPattern: '/en/resources/support-articles/release-notes/',
    matchKeywords: ['adrenalin', 'radeon', 'driver'],
    homeUrl: 'https://www.amd.com/en/support/download/drivers.html',
  },
  {
    id: 'intel-graphics-drivers',
    name: 'Intel Graphics Drivers',
    category: 'Software',
    kind: 'html',
    color: 0x0071c5,
    iconUrl: 'https://www.intel.com/favicon.ico',
    indexUrl:
      'https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html',
    linkPattern: '/content/www/us/en/download/',
    matchKeywords: ['graphics', 'arc', 'iris', 'driver'],
    homeUrl: 'https://www.intel.com/content/www/us/en/download-center/home.html',
  },
  {
    id: 'github-changelog',
    name: 'GitHub Changelog',
    category: 'Software',
    kind: 'rss',
    color: SOFTWARE_COLOR,
    rssUrl: 'https://github.blog/changelog/feed/',
    homeUrl: 'https://github.blog/changelog/',
  },
  {
    id: 'nodejs-blog',
    name: 'Node.js',
    category: 'Software',
    kind: 'rss',
    color: SOFTWARE_COLOR,
    rssUrl: 'https://nodejs.org/en/feed/blog.xml',
    homeUrl: 'https://nodejs.org/en/blog/',
  },
  {
    id: 'docker-blog',
    name: 'Docker',
    category: 'Software',
    kind: 'rss',
    color: SOFTWARE_COLOR,
    rssUrl: 'https://www.docker.com/blog/feed/',
    homeUrl: 'https://www.docker.com/blog/',
  },
];

export function getPatchSource(id: string): PatchSource | undefined {
  return PATCH_SOURCES.find((source) => source.id === id);
}

export function patchSourceLabel(id: string): string {
  return getPatchSource(id)?.name ?? id;
}
